### PR TITLE
Update Cutechess binaries to v1.2.0 cutechess/cutechess@3d1ac5b

### PR DESCRIPTION
**Pull request by ppigazzini**
Cutechess binaries built from v1.2.0 cutechess/cutechess@3d1ac5b
using these [instructions](https://github.com/ianfab/fishtest/wiki/Build-cutechess-with-Qt5-static).

``` bash
$ git log --online -n 5
3d1ac5b7 bump windows installer to version 1.2.0
72a4e5de update the windows installer
4aa5d11f cutechess 1.2.0
788cab77 Fix the initial ply count for bare king in ASEAN and Sittuyin
a9e60884 link to 'Building from source' wiki page
```

All files tested clean with VirusTotal

[cutechess-cli-win.zip](https://www.virustotal.com/gui/file/0ef5f037c3569627e5e51233f4f77ec22bb8102d99669e217379c53e977ad4eb/detection)

[cutechess-cli-linux-64bit.zip](https://www.virustotal.com/gui/file/b82ca4f9c00c30cda41ff35c05a0c8c5c6b3121b5b10a46afa9b1cbc1475ce75/detection)

[cutechess-cli-linux-32bit.zip](https://www.virustotal.com/gui/file/fb885811046922d7992d151dd7359e0dd206bffe7592816ea9ba48eedc6cc4c7/detection)

### CODE REVIEW

**Comment by ianfab** [comment]
Thanks a lot! In order to test the newly supported variants (like shogi), I will force a worker update by bumping the version perhaps around 17 UTC today. @notruck @ddugovic

**Comment by ddugovic** [comment]
Thanks, I'll be glad to update my worker once an update is available.

**Comment by ppigazzini** [comment]
@ianfab cutechess has raised the requirement to Qt5 >= 5.11 , however I was able to build cutechess with Qt5 5.10 on Ubuntu 14.04 simply disabling the version check in `cutechess.pro`: this hack could stop working in the future. In that case will be better to switch to a CentOS 7 toolchain (supported until 2024) to have a 64 bit only cutechess-cli built with latest version of Qt5 (devtoolset are released only for 64 bit CentOS, so no support for workers at 32 bit).

Here is the script for CentOS 7:
```bash
#!/bin/bash
# sudo bash make_cute.sh
# https://wiki.qt.io/Building_Qt_5_from_Git
# http://doc.qt.io/qt-5/linux-deployment.html

n_jobs=6

# update and install packages
yum check-update
#yum install -y yum-utils
#yum-builddep -y qt5-qtbase

yum install -y centos-release-scl
yum install -y devtoolset-7
source scl_source enable devtoolset-7
yum install -y git
yum install -y libxcb libxcb-devel xcb-util xcb-util-devel mesa-libGL-devel libxkbcommon-devel

# build Qt5 static
git clone https://code.qt.io/qt/qt5.git
cd qt5
git checkout 5.15
perl init-repository --module-subset=default,-qtwebengine
mkdir /opt/qt5-static
./configure -static -release -opensource -confirm-license -prefix /opt/qt5-static -nomake examples -nomake tests -nomake tools -skip qtwebengine -no-icu
make -j ${n_jobs}
make -j ${n_jobs} install

# build cutechess-cli and cutechess
cd
git clone https://github.com/cutechess/cutechess.git
cd cutechess

# checkout the latest tag
git fetch -p --tags --all
tag=$(git describe --tags `git rev-list --tags --max-count=1`)
git checkout ${tag} -b latest

git log --oneline -n 5 > ../cutechess.git.log
/opt/qt5-static/bin/qmake -config release
make -j ${n_jobs}
strip projects/cli/cutechess-cli
strip projects/gui/cutechess
zip -j9 ../cutechess-cli-linux-$(getconf LONG_BIT)bit.zip COPYING projects/cli/cutechess-cli
```

**Comment by notruck** [comment]
My workers are now on version 70. Is there anything I should be doing besides restarting the worker.py? 

I'm noticing "invalid FEN string" warnings on the minishogi and euroshogi tests. 

```
Started game 107 of 200 (stockfish vs base)
Warning: Invalid FEN string: rb1g1/2skp/5/P1G2/1KSBR[] w - - 0 1
Warning: The opening suite is incompatible with the current chess variant
Finished game 107 (stockfish vs base): 1-0 {Sente mates}
Score of stockfish vs base: 52 - 55 - 0  [0.486] 107
Started game 108 of 200 (base vs stockfish)
Warning: Invalid FEN string: rbs1k/3gp/5/PGS2/K2BR[] w - - 0 1
Warning: The opening suite is incompatible with the current chess variant
Finished game 108 (base vs stockfish): 1-0 {White wins by adjudication}
Score of stockfish vs base: 52 - 56 - 0  [0.481] 108
Started game 109 of 200 (stockfish vs base)
``` 
The PGN appears to contain minishogi games, but the opening lines seem repetitive with a lot of `1. Gb2 Bc4` at first glance.  [fishtest-v70-minishogi-pgn.zip](https://github.com/ianfab/FishCooking/files/5104953/fishtest-v70-minishogi-pgn.zip)

**Comment by ianfab** [comment]
Thanks for reporting, looks like cutechess skips the castling and en passant fields for shogi variants, so I will need to update the books.

**Comment by ianfab** [comment]
I updated the books, in local testing it seems to work fine now. @ppigazzini @notruck @ddugovic In order to force download of the book update, I could bump the worker version, but it might be easier if we all just remove the below books and restart the workers, then it should re-download them automatically. Sorry for the inconvenience.
`rm -f dobutsu.epd euroshogi.epd judkins.epd minishogi.epd shogi.epd`

**Comment by ppigazzini** [comment]
@ianfab done :)

**Comment by ppigazzini** [comment]
@ianfab cutechess bug with a proposed fixing, see https://github.com/cutechess/cutechess/issues/616
I don't know how many variants are affected.

**Comment by ianfab** [comment]
Thanks for the info. To my understanding this only affects chess960 and grid chess, neither of which is frequently tested on variantfishtest, so it should not be very critical. https://github.com/cutechess/cutechess/pull/611 and https://github.com/cutechess/cutechess/pull/615 are more relevant for variantfishtest as those bugs were already seen to be triggered on workers, which potentially introduces a slight noise and/or bias in the results for the affected variants.

**Pull request merged**
