### PR TITLE
Cutechess binaries updated to 14.01.2018

### PR DESCRIPTION
**Pull request by ppigazzini**
Cutechess binaries built using these instructions
https://github.com/ianfab/fishtest/wiki/Build-cutechess-with-Qt5-static

All versions tested clean on VirusTotal

[cutechess-cli-win.zip](https://www.virustotal.com/#/file/c48d71db8a1258917965c4570cc3e2c803ec81f899c20cdc01c673940799ea96/detection)

[cutechess-cli-linux-64bit.zip](https://www.virustotal.com/#/file/903d02a2e53524449cd4aac91889a1bf5765382361c72b9a63b7f6ae0beb7c36/detection)

[cutechess-cli-linux-32bit.zip](https://www.virustotal.com/#/file/7b17e0d203fbd2be60651669e7273eb484af05ecdfac678b0304ff9e022ccd2a/detection)

### CODE REVIEW

**Comment by ianfab** [comment]
@ppigazzini Thanks a lot. I assume they are based on cutechess master at the time you posted you were starting the build, i.e., https://github.com/cutechess/cutechess/commit/9018e6a91105698853e1c6fecdba4846ffdf16c6, is that correct?

@alwey Can https://github.com/cutechess/cutechess/issues/339 also affect functionality for Shatranj or is this only an issue for Courier?

**Comment by alwey** [comment]
@ianfab : This should only affect Courier, Shatranj should be OK. And Courier did not explode either.

**Comment by ianfab** [comment]
@alwey Ok, thanks, just wanted to be sure before merging.

**Comment by ppigazzini** [comment]
@ianfab 

$ git log --oneline
1f7a177 (HEAD -> master, origin/master, origin/HEAD) PGN timestamp tags
9018e6a Support Seirawan Chess
171f71d Support medieval chess: Shatranj and Courier

**Comment by ianfab** [comment]
@ppigazzini Thanks. I will now increase the worker version to make the workers update cutechess-cli.

**Pull request merged**
